//
//  TasksModels.swift
//  YesplanCS
//
//  Created by Techcc - FOH - Video on 24/03/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Tasks
{
  // MARK: Use cases
  
  enum FetchTasks
  {
    struct Request
    {
    }
    struct Response
    {
        var tasks: [Task]

    }
    struct ViewModel
    {
        struct DisplayedTask
        {
            var deadline: String
            var start: String
            var LabelTasksName: String
            var LabelTasksDue: String
            var LabelTasksStart: String
        }
        var displayedTasks: [DisplayedTask]
    }
  }
}
