//
//  TasksWorker.swift
//  YesplanCS
//
//  Created by Techcc - FOH - Video on 24/03/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class TasksWorker
{
    func doLoadTasks(completionHandler: @escaping (YesplanResult) -> Void)
    {
        let client = YesplanClient()
        client.getData(from: .tasks) { [weak self] result in
            //        completionHandler(result, _)
            
            switch result {
            case .success(let yesplanResult):
                guard let response = yesplanResult else { return }
                completionHandler(response)
            case .failure(let error):
                print("the error \(error)")
            }
        }
        
    }
}
