//
//  TasksPresenter.swift
//  YesplanCS
//
//  Created by Techcc - FOH - Video on 24/03/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TasksPresentationLogic
{
    func presentFetchedTasks(response: Tasks.FetchTasks.Response)
}

class TasksPresenter: TasksPresentationLogic
{
  weak var viewController: TasksDisplayLogic?
  
  // MARK: Do something
  
    func presentFetchedTasks(response: Tasks.FetchTasks.Response)
    {
        let displayedTasks: [Tasks.FetchTasks.ViewModel.DisplayedTask] = []
        for event in response.tasks {
            print(event)
//            let url = event.url
//            let id = event.id
//            let name = event.name ?? "no name"
//            let location = event.locations[0].name ?? "no location"
//            let defaultschedulestarttime = event.defaultschedulestarttime ?? "no defstarttime"
//            let groupName = event.group?.name ?? "no groupName"
            
//            let displayedTask = Tasks.FetchTasks.ViewModel.DisplayedTask(id: id, url: url, name: name, location: location, defaultschedulestarttime: defaultschedulestarttime, groupName: groupName)
//            displayedTasks.append(displayedTask)
        }
        //    print("displayedEvents: ", displayedEvents) // ok
        let viewModel = Tasks.FetchTasks.ViewModel(displayedTasks: displayedTasks)
        viewController?.displayFetchedTasks(viewModel: viewModel)
    }
}
