//
//  EventsModels.swift
//  YesplanCS
//
//  Created by Techcc - FOH - Video on 24/03/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Events
{
  // MARK: Use cases
  
    enum FetchEvents
  {
    struct Request
    {
        
    }
        
    struct Response: Decodable
    {
            let pagination: Pagination?
            let data: [Event]
    }
        
    struct ViewModel
    {
        struct DisplayedEvent
        {
            var id: String
            var url: String
            var name: String
            var location: String
            var defaultschedulestarttime: String
            var groupName: String
            var startdate: String
        }
        var displayedEvents: [(key: String, value: [Events.FetchEvents.ViewModel.DisplayedEvent])]
        
        
    }
  }
}

enum Statuses {
    // MARK: Use cases
    enum FetchStatuses
    {
        struct Request
        {
            
        }
        struct Response
        {
            var pagination: Pagination?
            var data: [Status]
        }
        struct ViewModel
        {
            struct DisplayedStatus
            {
                var name: String
               
            }
            var displayedStatuses: [DisplayedStatus]
        }
    }
}
