//
//  EventsWorker.swift
//  YesplanCS
//
//  Created by Techcc - FOH - Video on 24/03/18.
//  Copyright (c) 2018 Yesplan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class EventsWorker
{
  
  func doLoadEvents(completionHandler: @escaping (YesplanResult) -> Void)
  {
     let client = YesplanClient()
    client.getData(from: .events) { [weak self] result in
        switch result {
        case .success(let yesplanResult):
//            print("succes")
//            print("yesplanResult: ", yesplanResult)
            guard let response = yesplanResult else { return }
            print(response)
            completionHandler(response)
        case .failure(let error):
            print("failure")
            print("the error \(error)")
        }
    }
    
  }
    
  func doLoadStatuses(completionHandler: @escaping (YesplanResult) -> Void)
    {
        let client = YesplanClient()
        client.getData(from: .statuses) { [weak self] result in
            switch result {
            case .success(let yesplanResult):
                guard let response = yesplanResult else { return }
                completionHandler(response)
            case .failure(let error):
                print("error: \(error)")
            }
        }
        
    }
}
